version: '3'

###############################################################
# Volumes
###############################################################
volumes:
    prometheus_data: {}
    grafana_data: {}

###############################################################
# Network settings
###############################################################
networks:
  front-tier:
    external: true
  back-tier: {}

services:
  ###############################################################
  # NGINX
  ###############################################################
  nginx:
    container_name: nginx
    image: nginx-local
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - front-tier
      - back-tier
    links:
      - grafana:grafana
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/.htpasswd:/etc/nginx/conf.d/.htpasswd
      - ./nginx/grafana.conf:/etc/nginx/conf.d/grafana.conf
      - ./nginx/prometheus.conf:/etc/nginx/conf.d/prometheus.conf

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  ###############################################################
  # Grafana
  ###############################################################
  grafana:
    image: grafana/grafana:7.1.3
    container_name: grafana
    user: "104"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
    restart: always

  ###############################################################
  # Prometheus
  ###############################################################
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    networks:
      - back-tier
    restart: always

  ###############################################################
  # Internal Node exporter
  ###############################################################
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - back-tier
    restart: always

  ###############################################################
  # Alert Manager
  ###############################################################
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  ###############################################################
  # Local cadvisor
  ###############################################################
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - back-tier
    restart: always


  ###############################################################
  # Mysql Exporter
  ###############################################################
  mysqld_exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    environment:
      - DATA_SOURCE_NAME=root:prometheus@(localhost:3306)/ ##TODO Change to a DB mysql connection
    command:
      - '--collect.global_status'
      - '--collect.global_variables'
      - '--collect.binlog_size'
      - '--collect.info_schema.innodb_metrics'
      - '--collect.info_schema.processlist'
      - '--collect.info_schema.query_response_time'
      - '--collect.info_schema.tables'
      - '--collect.info_schema.tablestats'
      - '--collect.info_schema.schemastats'
      - '--collect.info_schema.userstats'
      - '--collect.perf_schema.eventswaits'
      - '--collect.perf_schema.file_events'
      - '--collect.perf_schema.tableiowaits'
      - '--collect.perf_schema.tablelocks'
    ports:
      - 9104:9104
    depends_on:
      - prometheus
    networks:
      - back-tier
    restart: always

  ###############################################################
  # Backbox Exporter
  ###############################################################
  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    volumes:
      - ./blackbox-exporter:/config
    ports:
      - 9115:9115
    depends_on:
      - prometheus
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/config/blackbox.yml'

  ###############################################################
  # Grafana Loki & promtail
  ###############################################################
  loki:
    image: grafana/loki:v1.0.0
    container_name: loki
    volumes:
      - ./grafana/loki/config.yaml:/etc/loki/local-config.yaml
    command: --config.file=/etc/loki/local-config.yaml
    networks:
      - back-tier

  promtail:
    image: grafana/promtail:1.6.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: --config.file=/etc/promtail/docker-config.yaml
    networks:
      - back-tier
