version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - /tmp:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= password
      - MYSQL_DATABASE= db
      - MYSQL_USER= prometheus
      - MYSQL_PASSWORD= prometheus
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - back-tier
      - front-tier
    ports:
      - 3306:3306
      - 33060:33060
